# Site settings
title:          Yingwei Guo's Blog
description:    ""
url:            "https://guoyingwei6.github.io"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Yingwei Guo
  url:          https://guoyingwei.top
  email:        guoyingwei6@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale